{% set name = "Clipboard" %}
{% set version = "0.9.1" %}

package:
  name: cb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Slackadays/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b59f7111c2de0369d80a379503ac056e33c59be34596d72cda600e4115002b60

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make  # [unix]
    - pkg-config  # [unix]
    - wayland-protocols  # [linux]

  host:
    - openssl
    - alsa-lib  # [linux]
    - xorg-libx11  # [linux]
    - wayland  # [linux]

test:
  commands:
    - cb --help

about:
  home: https://getclipboard.app
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Your new, **_ridonkuliciously_** smart clipboard manager
  description: |
    The Clipboard Project (CB for short) is the oh-so-awesome
    clipboard manager that's just like a second brain.
    It's fast and lightweight, feature packed, and super user friendly.
  dev_url: https://github.com/Slackadays/Clipboard
  doc_url: https://getclipboard.app/docs

extra:
  recipe-maintainers:
    - eunos-1128
    - Slackadays
